<?php
if ( !class_exists( 'Less_Parser' ) ) require_once( dirname( __FILE__ ) . '/Less.php' );

if ( !function_exists( 'nerdpress_compiler' ) ) :
/*
 * This function can be used to compile a less file to css using the lessphp compiler
 */
function nerdpress_compiler() {
	$minify_css = NerdPress::variable( 'minify_css' );
	$options = ( $minify_css == 1 ) ? array( 'compress'=>true ) : array( 'compress'=>false );
	
	$bootstrap_location = get_template_directory() . '/assets/less/';
	$webfont_location   = get_template_directory() . '/assets/fonts/';
	$bootstrap_uri      = '';
	$custom_less_file   = get_template_directory() . '/assets/less/custom.less';
	
	$parser = new Less_Parser( $options );
	
	// The main app.less file
	$parser->parseFile( $bootstrap_location . 'app.less', $bootstrap_uri );
	
	// The custom.less file
	if ( is_writable( $custom_less_file ) )
	$parser->parseFile( $bootstrap_location . 'custom.less', $bootstrap_uri );
	
	// Add a filter to the compiler
	$parser->parse( apply_filters( 'nerdpress_compiler', '' ) );
	
	$css = $parser->getCss();
	
	// Below is just an ugly hack
	$css = str_replace( 'bootstrap/fonts/', '', $css );
	return apply_filters( 'nerdpress_compiler_output', $css );
}
endif;


if ( !function_exists( 'nerdpress_makecss' ) ) :
function nerdpress_makecss( $method = 'php' ) {
  global $wp_filesystem;
  $file = nerdpress_css();
  
  // Initialize the Wordpress filesystem, no more using file_put_contents function
  if ( empty( $wp_filesystem ) ) {
    require_once( ABSPATH . '/wp-admin/includes/file.php' );
    WP_Filesystem();
  }

  $content = '/********* Do not edit this file *********/

';

  $content .= nerdpress_compiler();

  if ( is_writeable( $file ) || ( !file_exists( $file ) && is_writeable( dirname( $file ) ) ) ) {
    if ( !$wp_filesystem->put_contents( $file, $content, FS_CHMOD_FILE ) )
      return apply_filters( 'nerdpress_css_output', $content );
  }
}
endif;

/* ===== */

if ( !function_exists( 'nerdpress_css' ) ) :
/*
 * Gets the css path or url to the stylesheet
 * If $target = 'path', return the path
 * If $target = 'url', return the url
 *
 * If echo = true then print the path or url.
 */
function nerdpress_css( $target = 'path', $echo = false ) {
  global $blog_id;

  $defaultfile = '/assets/css/main.min';
  // If this is a multisite installation, append the blogid to the filename
  $cssid    = ( is_multisite() && $blog_id > 1 ) ? '_id-' . $blog_id : null;

  $css_uri  = get_template_directory_uri() . $defaultfile . $cssid . '.css';
  $css_path = get_template_directory() . $defaultfile . $cssid . '.css';

  if ( !is_writable( $css_path ) )
    $css_uri = get_template_directory_uri() . $defaultfile . '-default.css';

  if ( is_child_theme() ) {
    $child_style = get_stylesheet_directory() . $defaultfile . $cssid . '.css';
    $child_style_writable = ( is_writable( $child_style ) ) ? true : false;

    if ( $child_style_writable ) {
      $css_path = $child_style;
      $css_url  = get_stylesheet_directory_uri() . $defaultfile . $cssid . '.css';
      $css_uri  = get_template_directory_uri() . $defaultfile . '-default.css';
    }
  }

  $return = ( $target == 'url' ) ? $css_uri : $css_path;

  if ( $echo )
    echo $return;
  else
    return $return;
}
endif;


if ( !function_exists( 'nerdpress_css_not_writeable' ) ) :
/*
 * Admin notice if css is not writable
 */
function nerdpress_css_not_writeable( $array ) {
  global $current_screen, $wp_filesystem;

  if ( $current_screen->parent_base == 'themes' ) {
    $filename = nerdpress_css();
    $url = nerdpress_css('url');
    
    if ( !file_exists( $filename ) ) {
      if ( !$wp_filesystem->put_contents( $filename, ' ', FS_CHMOD_FILE ) ) {
        $content = __( 'The following file does not exist and must be so in order to utilise this theme. Please create this file.', 'nerdpress' );
        $content .= '<br>' . __( 'Try visiting the theme options and clicking the "Reset All" button to attempt automatically creating it.', 'nerdpress' );
        $content .= '<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="' . $filename . '" target="_blank">' . $filename . '</a>';
        add_settings_error( 'nerdpress', 'create_file', $content, 'error' );                  
        settings_errors();
      }
    } else {
      if ( !is_writable( $filename ) ) {
        $content = __( 'The following file is not writable and must be so in order to utilise this theme. Please update the permissions.', 'nerdpress' );
        $content .= '<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="' . $filename . '" target="_blank">' . $filename . '</a>';

        add_settings_error( 'nerdpress', 'create_file', $content, 'error' );                  
        settings_errors();
      }
    }
  }
}
endif;
add_action( 'admin_notices', 'nerdpress_css_not_writeable');


if ( !function_exists( 'nerdpress_process_font' ) ) :
function nerdpress_process_font( $font ) {
  
  if ( empty( $font['font-weight'] ) )
    $font['font-weight'] = "inherit";

  if ( empty( $font['font-style'] ) )
    $font['font-style'] = "inherit";

  if ( isset( $font['font-size'] ) )
    $font['font-size'] = filter_var( $font['font-size'], FILTER_SANITIZE_NUMBER_INT );

  return $font;
}
endif;

// If the Custom LESS exists and has changed after the last compilation, trigger the compiler.
if ( is_writable( get_template_directory() . '/assets/less/custom.less' ) ) {
  if ( filemtime( get_template_directory() . '/assets/less/custom.less' ) > filemtime( nerdpress_css() ) )
    nerdpress_makecss();
}